# Generated by Django 2.0.4 on 2018-04-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180411_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
