# Generated by Django 2.0.4 on 2018-04-10 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180410_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='productCategory',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', related_name='products', to='products.ProductCategory'),
        ),
    ]
