# Generated by Django 2.0.4 on 2018-04-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180410_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productCategory',
            new_name='category',
        ),
    ]
