# Generated by Django 2.0.4 on 2018-05-19 10:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_auto_20180501_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AddField(
            model_name='product',
            name='img0',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.CharField(blank=True, db_index=True, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.CharField(blank=True, db_index=True, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.CharField(blank=True, db_index=True, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='img4',
            field=models.CharField(blank=True, db_index=True, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='img5',
            field=models.CharField(blank=True, db_index=True, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='img6',
            field=models.CharField(blank=True, db_index=True, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.DecimalField(db_index=True, decimal_places=0, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_views',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='products_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(db_index=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
