# Generated by Django 2.0.4 on 2018-05-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180519_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_views',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
