# Generated by Django 2.0.4 on 2018-05-20 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180519_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
    ]
