# Generated by Django 2.0.4 on 2018-05-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_owner'),
        ('products', '0014_product_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img0',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img6',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='images_products', to='images.Image'),
        ),
    ]
