# Generated by Django 2.0.4 on 2018-05-01 15:09

import WhiteMarket.apps.images.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=WhiteMarket.apps.images.models.scramble_uploaded_filename, verbose_name='Uploaded image')),
                ('thumbnail', models.ImageField(blank=True, upload_to='', verbose_name='Thumbnail of uploaded image')),
                ('owner', models.ForeignKey(on_delete='models.CASCADE', related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
