# Generated by Django 2.0.4 on 2018-05-01 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0002_remove_image_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', related_name='images', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
